apiVersion: v1
kind: Pod
metadata:
  name: crash-loop-pod
  labels:
    app: test-crash
spec:
  containers:
  - name: crash-container
    image: busybox
    command: ['sh', '-c', 'exit 1']  # This command will cause the container to crash
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
  restartPolicy: Always  # The pod will restart repeatedly, causing a crash loop
