apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 5000  # External port to expose the service
      targetPort: 5000  # The port the Flask app is listening on inside the container
  type: LoadBalancer  # Expose the service on a port accessible from outside Minikube
