apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      scrape_timeout: 10s
      evaluation_interval: 1m

    rule_files:
    - /etc/prometheus-config/alert-rules.yml

    scrape_configs:
      - job_name: prometheus
        honor_timestamps: true
        scrape_interval: 5s
        scrape_timeout: 5s
        metrics_path: /metrics
        scheme: http
        follow_redirects: true
        static_configs:
          - targets:
              - localhost:9090

      - job_name: alertmanager
        honor_timestamps: true
        scrape_interval: 5s
        scrape_timeout: 5s
        metrics_path: /metrics
        scheme: http
        follow_redirects: true
        static_configs:
          - targets:
              - alertmanager:9093

      - job_name: kube-state-metrics
        honor_timestamps: true
        scrape_interval: 15s
        scrape_timeout: 10s
        metrics_path: /metrics
        scheme: http
        follow_redirects: true
        static_configs:
          - targets:
              - kube-state-metrics:8080
        
    alerting:
      alertmanagers:
      - static_configs:
        - targets: ['alertmanager:9093']

    
