apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: test-alert-rule
  namespace: default
  labels:
    release: prometheus
spec:
  groups:
    - name: test-group
      rules:
        - alert: AlwaysFiring
          expr: vector(1)
          for: 1m
          labels:
            severity: warning
          annotations:
            summary: "This is a test alert that always fires."
            description: "If you see this alert, then Prometheus rules are working."
